CREATE VIEW DEPARTAM AS
    SELECT DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC, COUNT(EMP.EMPNO) TOT_EMP, NVL(ROUND(SUM(EMP.SAL), 2), 0) TOT_SAL
    FROM EMP, DEPT
    WHERE EMP.DEPTNO (+) = DEPT.DEPTNO
    GROUP BY DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
    ORDER BY TOT_EMP DESC;
/

CREATE OR REPLACE TRIGGER ges_depart
    INSTEAD OF DELETE OR INSERT OR UPDATE
    ON DEPARTAM
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DEPT
        VALUES(:NEW.DEPTNO, :NEW.DNAME, :NEW.loc);
    ELSIF DELETING THEN
        DELETE FROM DEPT WHERE DEPTNO = :OLD.DEPTNO;
    ELSIF UPDATING('LOC') THEN
        UPDATE DEPT SET LOC = :NEW.LOC
        WHERE DEPTNO = :OLD.DEPTNO;
    ELSE
        RAISE_APPLICATION_ERROR (-20001,'Error en la actualización');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error en el trigger: ' || SQLERRM);
END;
/

SELECT * FROM DEPARTAM;