SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
FROM ALL_OBJECTS
WHERE OBJECT_TYPE IN ('FUNCTION','PROCEDURE')
AND OWNER = 'BD_SCOTT_JO'
ORDER BY OBJECT_TYPE;

SELECT * FROM ALL_OBJECTS WHERE OWNER = 'BD_SCOTT_JO';
